-- Jalankan file ini di Supabase SQL Editor sebelum deploy aplikasi.
-- Struktur tabel mengikuti database SQLite lama aplikasi pembelajaran ekosistem.

create table if not exists public.users (
    id_user bigint generated by default as identity primary key,
    nama text not null,
    email text not null unique,
    google_sub text unique,
    role text not null check (role in ('admin', 'guru', 'siswa')),
    kelas text default '',
    status text default 'aktif' check (status in ('aktif', 'nonaktif')),
    created_at text,
    updated_at text
);

create table if not exists public.tanggapan_siswa (
    id_tanggapan text primary key,
    waktu text not null,
    nama text not null,
    jenis_simulasi text not null,
    input_simulasi text not null,
    hasil_simulasi text not null,
    jawaban_1 text not null,
    jawaban_2 text not null,
    jawaban_3 text not null,
    kesimpulan text not null
);

create table if not exists public.feedback_guru (
    id_feedback text primary key,
    id_tanggapan text not null references public.tanggapan_siswa(id_tanggapan) on delete cascade,
    waktu_feedback text not null,
    nama_siswa text not null,
    nama_guru text not null,
    isi_feedback text not null
);

create table if not exists public.progress_siswa (
    id_progress bigint generated by default as identity primary key,
    nama text not null unique,
    materi_dibaca integer default 0,
    simulasi_dijalankan integer default 0,
    tanggapan_dikirim integer default 0,
    feedback_diterima integer default 0,
    updated_at text
);

create table if not exists public.progress_materi (
    id_progress_materi bigint generated by default as identity primary key,
    nama text not null,
    kode_materi text not null,
    judul_materi text not null,
    status_selesai integer default 1,
    updated_at text,
    constraint progress_materi_nama_kode_unique unique (nama, kode_materi)
);

create index if not exists idx_users_email on public.users(email);
create index if not exists idx_tanggapan_nama on public.tanggapan_siswa(nama);
create index if not exists idx_feedback_nama_siswa on public.feedback_guru(nama_siswa);
create index if not exists idx_progress_siswa_nama on public.progress_siswa(nama);
create index if not exists idx_progress_materi_nama on public.progress_materi(nama);

-- Karena aplikasi ini memakai Google OAuth custom dan query server-side dari Streamlit,
-- koneksi paling sederhana memakai secret/service key di Streamlit Secrets.
-- Jangan menaruh key tersebut di repository publik.

-- =====================================================
-- FONDASI GUIDED INQUIRY BERBASIS MISI
-- =====================================================
-- Untuk project lama, jalankan database/migrations/001_guided_inquiry.sql.

create table if not exists public.mission_progress (
    id_progress bigint generated by default as identity primary key,
    id_user bigint not null references public.users(id_user) on delete cascade,
    mission_code text not null check (mission_code in ('misi_1', 'misi_2', 'misi_3', 'misi_4')),
    current_stage text not null default 'fenomena' check (
        current_stage in ('fenomena', 'rumusan_masalah', 'hipotesis', 'penyelidikan', 'analisis', 'kesimpulan')
    ),
    status text not null default 'belum_dimulai' check (
        status in ('belum_dimulai', 'sedang_dikerjakan', 'selesai')
    ),
    started_at timestamptz,
    completed_at timestamptz,
    updated_at timestamptz not null default now(),
    constraint mission_progress_user_mission_unique unique (id_user, mission_code)
);

create table if not exists public.inquiry_responses (
    id_response bigint generated by default as identity primary key,
    id_user bigint not null references public.users(id_user) on delete cascade,
    mission_code text not null check (mission_code in ('misi_1', 'misi_2', 'misi_3', 'misi_4')),
    pengamatan text default '',
    rumusan_masalah text default '',
    hipotesis text default '',
    alasan_hipotesis text default '',
    variabel_bebas text default '',
    variabel_terikat text default '',
    variabel_kontrol text default '',
    analisis_pola text default '',
    bukti_data_1 text default '',
    bukti_data_2 text default '',
    hubungan_variabel text default '',
    status_hipotesis text check (
        status_hipotesis is null or status_hipotesis in ('didukung', 'didukung_sebagian', 'tidak_didukung')
    ),
    alasan_uji_hipotesis text default '',
    kesimpulan text default '',
    refleksi text default '',
    aksi_lingkungan text default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint inquiry_responses_user_mission_unique unique (id_user, mission_code)
);

create table if not exists public.experiment_runs (
    id_run bigint generated by default as identity primary key,
    id_user bigint not null references public.users(id_user) on delete cascade,
    mission_code text not null check (mission_code in ('misi_1', 'misi_2', 'misi_3', 'misi_4')),
    simulation_code text not null,
    run_number integer not null check (run_number > 0),
    input_data jsonb not null default '{}'::jsonb,
    output_data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint experiment_runs_user_mission_run_unique unique (id_user, mission_code, run_number)
);

create index if not exists idx_mission_progress_id_user on public.mission_progress(id_user);
create index if not exists idx_mission_progress_status on public.mission_progress(status);
create index if not exists idx_inquiry_responses_id_user on public.inquiry_responses(id_user);
create index if not exists idx_experiment_runs_user_mission on public.experiment_runs(id_user, mission_code);
