-- Jalankan file ini di Supabase SQL Editor sebelum deploy aplikasi.
-- Struktur tabel mengikuti database SQLite lama aplikasi pembelajaran ekosistem.

create table if not exists public.users (
    id_user bigint generated by default as identity primary key,
    nama text not null,
    email text not null unique,
    google_sub text unique,
    password_hash text,
    role text not null check (role in ('admin', 'guru', 'siswa')),
    kelas text default '',
    status text default 'aktif' check (status in ('aktif', 'nonaktif')),
    created_at text,
    updated_at text
);

create table if not exists public.tanggapan_siswa (
    id_tanggapan text primary key,
    waktu text not null,
    nama text not null,
    jenis_simulasi text not null,
    input_simulasi text not null,
    hasil_simulasi text not null,
    jawaban_1 text not null,
    jawaban_2 text not null,
    jawaban_3 text not null,
    kesimpulan text not null
);

create table if not exists public.feedback_guru (
    id_feedback text primary key,
    id_tanggapan text not null references public.tanggapan_siswa(id_tanggapan) on delete cascade,
    waktu_feedback text not null,
    nama_siswa text not null,
    nama_guru text not null,
    isi_feedback text not null
);

create table if not exists public.progress_siswa (
    id_progress bigint generated by default as identity primary key,
    nama text not null unique,
    materi_dibaca integer default 0,
    simulasi_dijalankan integer default 0,
    tanggapan_dikirim integer default 0,
    feedback_diterima integer default 0,
    updated_at text
);

create table if not exists public.progress_materi (
    id_progress_materi bigint generated by default as identity primary key,
    nama text not null,
    kode_materi text not null,
    judul_materi text not null,
    status_selesai integer default 1,
    updated_at text,
    constraint progress_materi_nama_kode_unique unique (nama, kode_materi)
);

create index if not exists idx_users_email on public.users(email);
create index if not exists idx_tanggapan_nama on public.tanggapan_siswa(nama);
create index if not exists idx_feedback_nama_siswa on public.feedback_guru(nama_siswa);
create index if not exists idx_progress_siswa_nama on public.progress_siswa(nama);
create index if not exists idx_progress_materi_nama on public.progress_materi(nama);

-- Jalankan baris ini juga pada database lama yang tabel users-nya sudah pernah dibuat
-- agar login email & password bisa berjalan tanpa membuat ulang tabel.
alter table public.users add column if not exists password_hash text;

-- Karena aplikasi ini memakai Google OAuth custom/email-password dan query server-side dari Streamlit,
-- koneksi paling sederhana memakai secret/service key di Streamlit Secrets.
-- Jangan menaruh key tersebut di repository publik.
