-- Migration 001: fondasi data Guided Inquiry berbasis empat misi.
-- Jalankan sekali di Supabase SQL Editor pada project yang sudah memiliki tabel public.users.
-- Migration ini tidak menghapus atau mengubah tabel lama.

begin;

create table if not exists public.mission_progress (
    id_progress bigint generated by default as identity primary key,
    id_user bigint not null references public.users(id_user) on delete cascade,
    mission_code text not null check (mission_code in ('misi_1', 'misi_2', 'misi_3', 'misi_4')),
    current_stage text not null default 'fenomena' check (
        current_stage in (
            'fenomena',
            'rumusan_masalah',
            'hipotesis',
            'penyelidikan',
            'analisis',
            'kesimpulan'
        )
    ),
    status text not null default 'belum_dimulai' check (
        status in ('belum_dimulai', 'sedang_dikerjakan', 'selesai')
    ),
    started_at timestamptz,
    completed_at timestamptz,
    updated_at timestamptz not null default now(),
    constraint mission_progress_user_mission_unique unique (id_user, mission_code)
);

create table if not exists public.inquiry_responses (
    id_response bigint generated by default as identity primary key,
    id_user bigint not null references public.users(id_user) on delete cascade,
    mission_code text not null check (mission_code in ('misi_1', 'misi_2', 'misi_3', 'misi_4')),

    -- Tahap 1: orientasi fenomena
    pengamatan text default '',

    -- Tahap 2: rumusan masalah
    rumusan_masalah text default '',

    -- Tahap 3: hipotesis dan variabel
    hipotesis text default '',
    alasan_hipotesis text default '',
    variabel_bebas text default '',
    variabel_terikat text default '',
    variabel_kontrol text default '',

    -- Tahap 5: analisis data dan pengujian hipotesis
    analisis_pola text default '',
    bukti_data_1 text default '',
    bukti_data_2 text default '',
    hubungan_variabel text default '',
    status_hipotesis text check (
        status_hipotesis is null or status_hipotesis in (
            'didukung', 'didukung_sebagian', 'tidak_didukung'
        )
    ),
    alasan_uji_hipotesis text default '',

    -- Tahap 6 dan tindak lanjut
    kesimpulan text default '',
    refleksi text default '',
    aksi_lingkungan text default '',

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint inquiry_responses_user_mission_unique unique (id_user, mission_code)
);

create table if not exists public.experiment_runs (
    id_run bigint generated by default as identity primary key,
    id_user bigint not null references public.users(id_user) on delete cascade,
    mission_code text not null check (mission_code in ('misi_1', 'misi_2', 'misi_3', 'misi_4')),
    simulation_code text not null,
    run_number integer not null check (run_number > 0),
    input_data jsonb not null default '{}'::jsonb,
    output_data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint experiment_runs_user_mission_run_unique unique (id_user, mission_code, run_number)
);

create index if not exists idx_mission_progress_id_user
    on public.mission_progress(id_user);
create index if not exists idx_mission_progress_status
    on public.mission_progress(status);
create index if not exists idx_inquiry_responses_id_user
    on public.inquiry_responses(id_user);
create index if not exists idx_experiment_runs_user_mission
    on public.experiment_runs(id_user, mission_code);

commit;
